##################### React Pro Boilerplate Configuration Defaults #####################
#
# Note: If change any config key or section, you shuold also update the type definition. details see /server/typings/config.ts.
#
#################################### Servers ###############################
doc_title = "React Pro Boilerplate"
[server]
# Protocol (http, https, h2, socket)
protocol = "http"

# The ip address to bind to, empty will bind to all interfaces
http_addr = ""

# The http port to use
http_port = 3001
 
# The public facing domain name used to access server from a browser
domain = "localhost"

# This is the a variale, generated as `${protocol}://${domain}:${http_port}/`, dot not config it in toml file.  TODO: add a toml variable parser
# root_url = ""

# This is the path url of root_url, use for base tag
app_sub_url = ""

# The root path of static resource
static_root_path = "dist" 

# Enable gzip
enable_gzip = false

# Https certs & key file
cert_file = ""
cert_key = ""
ca = ""

[proxy]
# enable proxy
enable = false
# Determine which requests should be proxied to the target host.
context = "/"
# Target host to proxy to
target = ""
# Changes the origin of the host header to the target URL
change_origin = true
#################################### Users ###############################
[auth]
# Login cookie name
login_cookie_name = "session"

# URL to redirect the user to if user visit without login cookie name
login_url = ""

# URL to redirect the user to after sign out
signout_redirect_url = ""

#################################### Logging #############################
[log]
# the enabled log transport, do not forget update the config type definiton if you modified this value becasuse is affectted in config structure!!!
transports = ["console","desc"]

# Directory where server can store logs
store_path = "log"


# Either "debug", "info", "warn", "error", "fatal", default is "info".see details at:https://github.com/log4js-node/log4js-node
level = "info"


# (temporary not support)  optional settings to set different levels for specific loggers. Ex filters = sqlstore:debug
# filters = ""

[log.console]

# Either "debug", "info", "warn", "error", "fatal", default is "info".see details at:https://github.com/log4js-node/log4js-node
level = "info"

# Either "stdout", "console", "file". default is "stdout".
appender_type = "console"

# (temporary not support)  log line format, valid options are text, console and json
# format = "console"


[log.desc]

# Either "debug", "info", "warn", "error", "fatal", default is "info".see details at:https://github.com/log4js-node/log4js-node
level = "info"

filename = 'desc.log'

# Either "stdout", "console", "file". default is "stdout".
appender_type = "file"

# (temporary not support)  log line format, valid options are text, console and json
# format = "text"

# This enables automated log rotate(switch of following options), default is true
log_rotate = true

# (temporary not support) Max line number of single file, default is 1000000
# max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB
max_size_shift = 28

# Segment log daily, default is true
daily_rotate = true

# Expired days of log file(delete after max days), default is 7
max_days =  7
